
[[constraint]]
  name = "github.com/labstack/echo"
  version = "3.3.6"

[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "1.3.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.1.1"

[[override]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/bakatz/echo-logrusmiddleware"